# Generated by Django 2.2.5 on 2020-11-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_auto_20201109_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
