# Generated by Django 2.2.5 on 2020-11-09 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_auto_20201109_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
